language: java
jdk:
- oraclejdk8
script: mvn sonar:sonar -Dsonar.projectKey=BlockAppDev_BlockApp -Dsonar.organization=blockappdev -Dsonar.host.url="https://sonarcloud.io" -Dsonar.login=6d6c802797c22ac51ebce197f4d03e3e82a1849e
